version: '3'

services:
  app:
    container_name: crud-portfolio-api
    restart: always
    build: .
    ports:
      - '5000:3000'
    links:
      - mongo
    environment:
      DB_SERVER: mongoDB
      PORT: $PORT

  mongo:
    container_name: mongoDB
    image: mongo:4.1.6
    ports:
      - '27017:27017'
